export enum ROLE {
  ADMIN = 'ADMIN',
  CUSTOMER = 'CUSTOMER',
}

export enum EVENT_ENUM {
  WEATHER = 'WEATHER',
  REMINDER = 'REMINDER',
  EXCHANGE = 'EXCHANGE',
}

export enum APP_TYPE_ENUM {
  DEFAULT = 0,
  WEATHER_REQUEST = 1,
  TASK_STORE_TYPE_DEFAULT = 2,
  TASK_STORE_TYPE_WEATHER = 3,
  TASK_STORE_TYPE_REMINDER = 4,
  TASK_STORE_TYPE_EXCHANGE = 11,
  TASK_DELETE = 5,
  EXCHANGE_START = 6,
  EXCHANGE_STORE_TYPE_SOURCE_CURRENCY = 7,
  EXCHANGE_STORE_TYPE_TARGET_CURRENCY = 8,
  SETTINGS = 9,
  TASK_UPDATE = 10,
}

export const EVENT_OPTIONS: { [key: string]: EVENT_ENUM } = {
  [APP_TYPE_ENUM.TASK_STORE_TYPE_WEATHER]: EVENT_ENUM.WEATHER,
  [APP_TYPE_ENUM.TASK_STORE_TYPE_REMINDER]: EVENT_ENUM.REMINDER,
  [APP_TYPE_ENUM.TASK_STORE_TYPE_EXCHANGE]: EVENT_ENUM.EXCHANGE,
};

export enum TOKEN_TYPE {
  REFRESH = 'refresh',
}
